In [ ]:
import pandas as pd

In [ ]:
# Path to data spreadsheet i CSV format!
data = pd.read_csv("./data/Interns_2025_SWIFT_CODES - Sheet1")

In [7]:
data

,COUNTRY ISO2 CODE,SWIFT CODE,CODE TYPE,NAME,ADDRESS,TOWN NAME,COUNTRY NAME,TIME ZONE
0,AL,AAISALTRXXX,BIC11,UNITED BANK OF ALBANIA SH.A,"HYRJA 3 RR. DRITAN HOXHA ND. 11 TIRANA, TIRANA...",TIRANA,ALBANIA,Europe/Tirane
1,BG,ABIEBGS1XXX,BIC11,ABV INVESTMENTS LTD,"TSAR ASEN 20 VARNA, VARNA, 9002",VARNA,BULGARIA,Europe/Sofia
2,BG,ADCRBGS1XXX,BIC11,ADAMANT CAPITAL PARTNERS AD,"JAMES BOURCHIER BLVD 76A HILL TOWER SOFIA, SOF...",SOFIA,BULGARIA,Europe/Sofia
3,UY,AFAAUYM1XXX,BIC11,AFINIDAD A.F.A.P.S.A.,"PLAZA INDEPENDENCIA 743 MONTEVIDEO, MONTEVIDE...",MONTEVIDEO,URUGUAY,America/Montevideo
4,MC,AGRIMCM1XXX,BIC11,CREDIT AGRICOLE MONACO (CRCA PROVENCE COTE D'A...,"23 BOULEVARD PRINCESSE CHARLOTTE MONACO, MONA...",MONACO,MONACO,Europe/Monaco
...,...,...,...,...,...,...,...,...
1056,AL,STANALTAXXX,BIC11,BANK OF ALBANIA,"TIRANA, TIRANA, 1001",TIRANA,ALBANIA,Europe/Tirane
1057,LV,IDXOLV22TIP,BIC11,AS INDEXO BANKA,"ELIZABETES STREET 13-1A RIGA, RIGA, LV-1010",RIGA,LATVIA,Europe/Riga
1058,PL,KCCPPLPW1AM,BIC11,KDPW CCP,"KSIAZECA 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw
1059,PL,KDPWPLPAASD,BIC11,KRAJOWY DEPOZYT PAPIEROW WARTOSCIOWYCH SPOLKA ...,"KSIAZECA 4 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw
1060,AL,PYALALT2XXX,BIC11,PAYSERA ALBANIA,"PALLATI DONIKA, FLOOR KATI 3 RR. FADIL RADA TI...",TIRANA,ALBANIA,Europe/Tirane

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   COUNTRY ISO2 CODE  1061 non-null   object
 1   SWIFT CODE         1061 non-null   object
 2   CODE TYPE          1061 non-null   object
 3   NAME               1061 non-null   object
 4   ADDRESS            1061 non-null   object
 5   TOWN NAME          1061 non-null   object
 6   COUNTRY NAME       1061 non-null   object
 7   TIME ZONE          1061 non-null   object
dtypes: object(8)
memory usage: 66.4+ KB

In [41]:
data.isna().sum()

COUNTRY ISO2 CODE    0
SWIFT CODE           0
CODE TYPE            0
NAME                 0
ADDRESS              0
TOWN NAME            0
COUNTRY NAME         0
TIME ZONE            0
dtype: int64

In [45]:
for col in data:
    data[col] = data[col].astype(str).str.strip()

In [46]:
data

,COUNTRY ISO2 CODE,SWIFT CODE,CODE TYPE,NAME,ADDRESS,TOWN NAME,COUNTRY NAME,TIME ZONE
0,AL,AAISALTRXXX,BIC11,UNITED BANK OF ALBANIA SH.A,"HYRJA 3 RR. DRITAN HOXHA ND. 11 TIRANA, TIRANA...",TIRANA,ALBANIA,Europe/Tirane
1,BG,ABIEBGS1XXX,BIC11,ABV INVESTMENTS LTD,"TSAR ASEN 20 VARNA, VARNA, 9002",VARNA,BULGARIA,Europe/Sofia
2,BG,ADCRBGS1XXX,BIC11,ADAMANT CAPITAL PARTNERS AD,"JAMES BOURCHIER BLVD 76A HILL TOWER SOFIA, SOF...",SOFIA,BULGARIA,Europe/Sofia
3,UY,AFAAUYM1XXX,BIC11,AFINIDAD A.F.A.P.S.A.,"PLAZA INDEPENDENCIA 743 MONTEVIDEO, MONTEVIDE...",MONTEVIDEO,URUGUAY,America/Montevideo
4,MC,AGRIMCM1XXX,BIC11,CREDIT AGRICOLE MONACO (CRCA PROVENCE COTE D'A...,"23 BOULEVARD PRINCESSE CHARLOTTE MONACO, MONA...",MONACO,MONACO,Europe/Monaco
...,...,...,...,...,...,...,...,...
1056,AL,STANALTAXXX,BIC11,BANK OF ALBANIA,"TIRANA, TIRANA, 1001",TIRANA,ALBANIA,Europe/Tirane
1057,LV,IDXOLV22TIP,BIC11,AS INDEXO BANKA,"ELIZABETES STREET 13-1A RIGA, RIGA, LV-1010",RIGA,LATVIA,Europe/Riga
1058,PL,KCCPPLPW1AM,BIC11,KDPW CCP,"KSIAZECA 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw
1059,PL,KDPWPLPAASD,BIC11,KRAJOWY DEPOZYT PAPIEROW WARTOSCIOWYCH SPOLKA ...,"KSIAZECA 4 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw
1060,AL,PYALALT2XXX,BIC11,PAYSERA ALBANIA,"PALLATI DONIKA, FLOOR KATI 3 RR. FADIL RADA TI...",TIRANA,ALBANIA,Europe/Tirane

In [49]:
for col in data:
    print(col,(data[col]=="").sum())

COUNTRY ISO2 CODE 0
SWIFT CODE 0
CODE TYPE 0
NAME 0
ADDRESS 86
TOWN NAME 0
COUNTRY NAME 0
TIME ZONE 0

Based on excersice description, and data format that API reutrns i will take the following approach: 
1. Based on `SWIFT CODE` column create  `isHeadquarter` [bool]
2. Delete redundant coluns - `CODE TYPE	` , `TOWN NAME` , `TIME ZONE` 
3. Allow every columns except `COUNTRY ISO2 CODE` and `SWIFT CODE` to be optional (not required) 
4. Rename columns accordingly to data base and pydentic models requirements

In [10]:
data = data.rename(
    columns={
        "SWIFT CODE": "swiftCode",
        "NAME": "bankName",
        "ADDRESS": "address",
        "COUNTRY ISO2 CODE": "countryISO2",
        "COUNTRY NAME": "countryName",
    }
)

In [11]:
data

,countryISO2,swiftCode,CODE TYPE,bankName,address,TOWN NAME,countryName,TIME ZONE
0,AL,AAISALTRXXX,BIC11,UNITED BANK OF ALBANIA SH.A,"HYRJA 3 RR. DRITAN HOXHA ND. 11 TIRANA, TIRANA...",TIRANA,ALBANIA,Europe/Tirane
1,BG,ABIEBGS1XXX,BIC11,ABV INVESTMENTS LTD,"TSAR ASEN 20 VARNA, VARNA, 9002",VARNA,BULGARIA,Europe/Sofia
2,BG,ADCRBGS1XXX,BIC11,ADAMANT CAPITAL PARTNERS AD,"JAMES BOURCHIER BLVD 76A HILL TOWER SOFIA, SOF...",SOFIA,BULGARIA,Europe/Sofia
3,UY,AFAAUYM1XXX,BIC11,AFINIDAD A.F.A.P.S.A.,"PLAZA INDEPENDENCIA 743 MONTEVIDEO, MONTEVIDE...",MONTEVIDEO,URUGUAY,America/Montevideo
4,MC,AGRIMCM1XXX,BIC11,CREDIT AGRICOLE MONACO (CRCA PROVENCE COTE D'A...,"23 BOULEVARD PRINCESSE CHARLOTTE MONACO, MONA...",MONACO,MONACO,Europe/Monaco
...,...,...,...,...,...,...,...,...
1056,AL,STANALTAXXX,BIC11,BANK OF ALBANIA,"TIRANA, TIRANA, 1001",TIRANA,ALBANIA,Europe/Tirane
1057,LV,IDXOLV22TIP,BIC11,AS INDEXO BANKA,"ELIZABETES STREET 13-1A RIGA, RIGA, LV-1010",RIGA,LATVIA,Europe/Riga
1058,PL,KCCPPLPW1AM,BIC11,KDPW CCP,"KSIAZECA 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw
1059,PL,KDPWPLPAASD,BIC11,KRAJOWY DEPOZYT PAPIEROW WARTOSCIOWYCH SPOLKA ...,"KSIAZECA 4 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw
1060,AL,PYALALT2XXX,BIC11,PAYSERA ALBANIA,"PALLATI DONIKA, FLOOR KATI 3 RR. FADIL RADA TI...",TIRANA,ALBANIA,Europe/Tirane

In [12]:
data["isHeadquarter"] = data["swiftCode"].str.endswith("XXX")

In [13]:
data

,countryISO2,swiftCode,CODE TYPE,bankName,address,TOWN NAME,countryName,TIME ZONE,isHeadquarter
0,AL,AAISALTRXXX,BIC11,UNITED BANK OF ALBANIA SH.A,"HYRJA 3 RR. DRITAN HOXHA ND. 11 TIRANA, TIRANA...",TIRANA,ALBANIA,Europe/Tirane,True
1,BG,ABIEBGS1XXX,BIC11,ABV INVESTMENTS LTD,"TSAR ASEN 20 VARNA, VARNA, 9002",VARNA,BULGARIA,Europe/Sofia,True
2,BG,ADCRBGS1XXX,BIC11,ADAMANT CAPITAL PARTNERS AD,"JAMES BOURCHIER BLVD 76A HILL TOWER SOFIA, SOF...",SOFIA,BULGARIA,Europe/Sofia,True
3,UY,AFAAUYM1XXX,BIC11,AFINIDAD A.F.A.P.S.A.,"PLAZA INDEPENDENCIA 743 MONTEVIDEO, MONTEVIDE...",MONTEVIDEO,URUGUAY,America/Montevideo,True
4,MC,AGRIMCM1XXX,BIC11,CREDIT AGRICOLE MONACO (CRCA PROVENCE COTE D'A...,"23 BOULEVARD PRINCESSE CHARLOTTE MONACO, MONA...",MONACO,MONACO,Europe/Monaco,True
...,...,...,...,...,...,...,...,...,...
1056,AL,STANALTAXXX,BIC11,BANK OF ALBANIA,"TIRANA, TIRANA, 1001",TIRANA,ALBANIA,Europe/Tirane,True
1057,LV,IDXOLV22TIP,BIC11,AS INDEXO BANKA,"ELIZABETES STREET 13-1A RIGA, RIGA, LV-1010",RIGA,LATVIA,Europe/Riga,False
1058,PL,KCCPPLPW1AM,BIC11,KDPW CCP,"KSIAZECA 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw,False
1059,PL,KDPWPLPAASD,BIC11,KRAJOWY DEPOZYT PAPIEROW WARTOSCIOWYCH SPOLKA ...,"KSIAZECA 4 4 WARSZAWA, MAZOWIECKIE, 00-498",WARSZAWA,POLAND,Europe/Warsaw,False
1060,AL,PYALALT2XXX,BIC11,PAYSERA ALBANIA,"PALLATI DONIKA, FLOOR KATI 3 RR. FADIL RADA TI...",TIRANA,ALBANIA,Europe/Tirane,True

In [14]:
data.columns

Index(['countryISO2', 'swiftCode', 'CODE TYPE', 'bankName', 'address',
       'TOWN NAME', 'countryName', 'TIME ZONE', 'isHeadquarter'],
      dtype='object')

In [16]:
needed_columns = [
    "countryISO2",
    "swiftCode",
    "bankName",
    "address",
    "countryName",
    "isHeadquarter",
]

relevant_data = data[needed_columns]
relevant_data

,countryISO2,swiftCode,bankName,address,countryName,isHeadquarter
0,AL,AAISALTRXXX,UNITED BANK OF ALBANIA SH.A,"HYRJA 3 RR. DRITAN HOXHA ND. 11 TIRANA, TIRANA...",ALBANIA,True
1,BG,ABIEBGS1XXX,ABV INVESTMENTS LTD,"TSAR ASEN 20 VARNA, VARNA, 9002",BULGARIA,True
2,BG,ADCRBGS1XXX,ADAMANT CAPITAL PARTNERS AD,"JAMES BOURCHIER BLVD 76A HILL TOWER SOFIA, SOF...",BULGARIA,True
3,UY,AFAAUYM1XXX,AFINIDAD A.F.A.P.S.A.,"PLAZA INDEPENDENCIA 743 MONTEVIDEO, MONTEVIDE...",URUGUAY,True
4,MC,AGRIMCM1XXX,CREDIT AGRICOLE MONACO (CRCA PROVENCE COTE D'A...,"23 BOULEVARD PRINCESSE CHARLOTTE MONACO, MONA...",MONACO,True
...,...,...,...,...,...,...
1056,AL,STANALTAXXX,BANK OF ALBANIA,"TIRANA, TIRANA, 1001",ALBANIA,True
1057,LV,IDXOLV22TIP,AS INDEXO BANKA,"ELIZABETES STREET 13-1A RIGA, RIGA, LV-1010",LATVIA,False
1058,PL,KCCPPLPW1AM,KDPW CCP,"KSIAZECA 4 WARSZAWA, MAZOWIECKIE, 00-498",POLAND,False
1059,PL,KDPWPLPAASD,KRAJOWY DEPOZYT PAPIEROW WARTOSCIOWYCH SPOLKA ...,"KSIAZECA 4 4 WARSZAWA, MAZOWIECKIE, 00-498",POLAND,False
1060,AL,PYALALT2XXX,PAYSERA ALBANIA,"PALLATI DONIKA, FLOOR KATI 3 RR. FADIL RADA TI...",ALBANIA,True